# Site settings
title: Rafael de Paula | iOS Developer
description: Senior iOS Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rafael de Paula
user_description: Senior iOS Developer, problem solver, passionate about making dazzling apps that improve the lives of people.
user_title: iOS Developer
email: rafsouzap@icloud.com
twitter_username: rafaelsdp
github_username:  rafsouzap
linkedin_username: rafadepaula

# Google-analytics
google-analytics:
  id: "UA-126666008-1"

exclude: ['package.json', 'src' , 'node_modules']
